name: SecureFlow CI/CD

on: [push, pull_request]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Snyk
        run: npm install -g snyk

      - name: Install project dependencies
        run: npm install

      - name: Check SNYK_TOKEN presence
        run: echo "Token set"
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


      - name: Run Snyk Scan
        run: snyk test --all-projects || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


      - name: Run Snyk Scan
        run: snyk test --all-projects

      - name: Run OWASP ZAP
        run: docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py -t http://your-url -r zap-report.html

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            zap-report.html