name: SecureFlow CI/CD

on: [push, pull_request]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Snyk
        run: npm install -g snyk

      - name: Auth Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Scan
        run: snyk test --all-projects

      - name: Run OWASP ZAP
        run: docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py -t http://your-url -r zap-report.html

      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: security-reports
          path: |
            zap-report.html